!> Checks RADIAL_OPERATORS' ADD_CURVATURE_TERM: must subtract exactly
!> l(l+1)/r(i)**2 from every diagonal entry i, and leave every
!> off-diagonal entry untouched.
PROGRAM TEST_RADIAL_OPERATORS
USE KINDS,             ONLY: dp, i4
USE GRID_RADIAL,       ONLY: RADIAL_GRID_T, BUILD_RADIAL_GRID
USE RADIAL_OPERATORS,  ONLY: RADIAL_OPERATOR_T, BUILD_RADIAL_OPERATORS, &
                              ADD_CURVATURE_TERM
IMPLICIT NONE

INTEGER(KIND=i4), PARAMETER :: N_R   = 20
REAL(KIND=dp),    PARAMETER :: R_MIN = 0.5_dp
REAL(KIND=dp),    PARAMETER :: R_MAX = 1.0_dp
INTEGER(KIND=i4), PARAMETER :: L     = 5

TYPE(RADIAL_GRID_T)     :: RGRID
TYPE(RADIAL_OPERATOR_T) :: OPS
REAL(KIND=dp), ALLOCATABLE :: OP_TEST(:,:)
REAL(KIND=dp) :: MAX_DIAG_ERR, MAX_OFFDIAG_ERR, EXPECTED
INTEGER(KIND=i4) :: I, J, N_FAIL

CALL BUILD_RADIAL_GRID(RGRID, N_R, R_MIN, R_MAX, FULL_SPHERE=.FALSE.)
CALL BUILD_RADIAL_OPERATORS(OPS, RGRID)

ALLOCATE(OP_TEST(N_R,N_R))
OP_TEST = OPS%D2
CALL ADD_CURVATURE_TERM(OP_TEST, L, RGRID)

MAX_DIAG_ERR = 0.0_dp
DO I = 1, N_R
  EXPECTED = OPS%D2(I,I) - REAL(L*(L+1), KIND=dp)/RGRID%R(I)**2
  MAX_DIAG_ERR = MAX(MAX_DIAG_ERR, ABS(OP_TEST(I,I)-EXPECTED))
END DO

MAX_OFFDIAG_ERR = 0.0_dp
DO J = 1, N_R
  DO I = 1, N_R
    IF (I /= J) THEN
      MAX_OFFDIAG_ERR = MAX(MAX_OFFDIAG_ERR, ABS(OP_TEST(I,J)-OPS%D2(I,J)))
    END IF
  END DO
END DO

N_FAIL = 0
IF (MAX_DIAG_ERR > 1.0E-14_dp .OR. MAX_OFFDIAG_ERR > 1.0E-14_dp) THEN
  N_FAIL = N_FAIL + 1
  WRITE(*,'(A,ES10.3,A,ES10.3)') "FAIL  curvature_term  diag_err=", MAX_DIAG_ERR, &
    "  offdiag_err=", MAX_OFFDIAG_ERR
ELSE
  WRITE(*,'(A)') "PASS  curvature_term"
END IF
DEALLOCATE(OP_TEST)

IF (N_FAIL > 0) THEN
  WRITE(*,'(A,I0,A)') "RESULT: FAILED - ", N_FAIL, " check(s) failed"
  STOP 1
ELSE
  WRITE(*,'(A)') "RESULT: PASSED - test_radial_operators"
END IF

END PROGRAM TEST_RADIAL_OPERATORS
