MODULE FIELD_TYPES
!> Spectral and physical-space field representations shared by every
!> regime. Spectral scalar/vector coefficients are indexed exactly as
!> FORTVSH's own YLM_INDEX(l,m) (no re-packing), radius as the leading
!> array dimension.
!>
!> SPECTRAL_VECTOR3_T stores FORTVSH's own three independent basis
!> coefficients (radial/poloidal/toroidal, in the PVSH_RAD/PVSH_POL/
!> PVSH_TOR sense -- three unrelated numbers spanning a general vector at
!> each (l,m), not the classic MHD "poloidal potential" convention where
!> B_r is a derivative of a single potential). A regime that wants a
!> solenoidal poloidal/toroidal potential pair (P,T) builds it out of a
!> SPECTRAL_SCALAR_T for each potential plus RADIAL_OPERATORS, and is
!> responsible for converting to/from SPECTRAL_VECTOR3_T itself when it
!> needs physical-space values.
USE KINDS, ONLY: dp, i4
IMPLICIT NONE
PRIVATE
PUBLIC :: SPECTRAL_SCALAR_T, SPECTRAL_VECTOR3_T, PHYSICAL_SCALAR_T, PHYSICAL_VECTOR_T
PUBLIC :: ALLOC_SPECTRAL_SCALAR, ALLOC_SPECTRAL_VECTOR3
PUBLIC :: ALLOC_PHYSICAL_SCALAR, ALLOC_PHYSICAL_VECTOR

TYPE :: SPECTRAL_SCALAR_T
  INTEGER(KIND=i4) :: N_R = 0, LMAX = 0, NLM = 0
  COMPLEX(KIND=dp), ALLOCATABLE :: COEF(:,:)   ! (N_R, NLM)
END TYPE SPECTRAL_SCALAR_T

TYPE :: SPECTRAL_VECTOR3_T
  INTEGER(KIND=i4) :: N_R = 0, LMAX = 0, NLM = 0
  COMPLEX(KIND=dp), ALLOCATABLE :: RAD(:,:), POL(:,:), TOR(:,:)   ! (N_R, NLM)
END TYPE SPECTRAL_VECTOR3_T

TYPE :: PHYSICAL_SCALAR_T
  INTEGER(KIND=i4) :: N_R = 0, NTHETA = 0, NPHI = 0
  REAL(KIND=dp), ALLOCATABLE :: F(:,:,:)       ! (N_R, NTHETA, NPHI)
END TYPE PHYSICAL_SCALAR_T

TYPE :: PHYSICAL_VECTOR_T
  INTEGER(KIND=i4) :: N_R = 0, NTHETA = 0, NPHI = 0
  REAL(KIND=dp), ALLOCATABLE :: R(:,:,:), TH(:,:,:), PH(:,:,:)
END TYPE PHYSICAL_VECTOR_T

CONTAINS

SUBROUTINE ALLOC_SPECTRAL_SCALAR(FIELD, N_R, LMAX)
  TYPE(SPECTRAL_SCALAR_T), INTENT(OUT) :: FIELD
  INTEGER(KIND=i4), INTENT(IN) :: N_R, LMAX
  FIELD%N_R = N_R; FIELD%LMAX = LMAX; FIELD%NLM = (LMAX+1)**2
  ALLOCATE(FIELD%COEF(N_R, FIELD%NLM))
  FIELD%COEF = (0.0_dp, 0.0_dp)
END SUBROUTINE ALLOC_SPECTRAL_SCALAR

SUBROUTINE ALLOC_SPECTRAL_VECTOR3(FIELD, N_R, LMAX)
  TYPE(SPECTRAL_VECTOR3_T), INTENT(OUT) :: FIELD
  INTEGER(KIND=i4), INTENT(IN) :: N_R, LMAX
  FIELD%N_R = N_R; FIELD%LMAX = LMAX; FIELD%NLM = (LMAX+1)**2
  ALLOCATE(FIELD%RAD(N_R, FIELD%NLM))
  ALLOCATE(FIELD%POL(N_R, FIELD%NLM))
  ALLOCATE(FIELD%TOR(N_R, FIELD%NLM))
  FIELD%RAD = (0.0_dp, 0.0_dp)
  FIELD%POL = (0.0_dp, 0.0_dp)
  FIELD%TOR = (0.0_dp, 0.0_dp)
END SUBROUTINE ALLOC_SPECTRAL_VECTOR3

SUBROUTINE ALLOC_PHYSICAL_SCALAR(FIELD, N_R, NTHETA, NPHI)
  TYPE(PHYSICAL_SCALAR_T), INTENT(OUT) :: FIELD
  INTEGER(KIND=i4), INTENT(IN) :: N_R, NTHETA, NPHI
  FIELD%N_R = N_R; FIELD%NTHETA = NTHETA; FIELD%NPHI = NPHI
  ALLOCATE(FIELD%F(N_R, NTHETA, NPHI))
  FIELD%F = 0.0_dp
END SUBROUTINE ALLOC_PHYSICAL_SCALAR

SUBROUTINE ALLOC_PHYSICAL_VECTOR(FIELD, N_R, NTHETA, NPHI)
  TYPE(PHYSICAL_VECTOR_T), INTENT(OUT) :: FIELD
  INTEGER(KIND=i4), INTENT(IN) :: N_R, NTHETA, NPHI
  FIELD%N_R = N_R; FIELD%NTHETA = NTHETA; FIELD%NPHI = NPHI
  ALLOCATE(FIELD%R(N_R, NTHETA, NPHI))
  ALLOCATE(FIELD%TH(N_R, NTHETA, NPHI))
  ALLOCATE(FIELD%PH(N_R, NTHETA, NPHI))
  FIELD%R = 0.0_dp; FIELD%TH = 0.0_dp; FIELD%PH = 0.0_dp
END SUBROUTINE ALLOC_PHYSICAL_VECTOR

END MODULE FIELD_TYPES
